import React from 'react';
import {
    AlignLeft,
    Archive,
    ArrowDownUp,
    ArrowRight,
    ArrowUp,
    BarChart3,
    Bug,
    CalendarDays,
    CalendarPlus,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    CircleAlert,
    CircleCheck,
    CirclePlus,
    Clock3,
    Columns3,
    CornerDownRight,
    Download,
    Eye,
    File,
    Flag,
    FolderKanban,
    GanttChartSquare,
    GripVertical,
    History,
    Inbox,
    Layers3,
    Link,
    List,
    ListFilter,
    ListPlus,
    ListTodo,
    ListTree,
    Maximize2,
    Menu,
    MessageSquare,
    Minimize2,
    MoreHorizontal,
    Move,
    Paperclip,
    Pencil,
    Plus,
    Printer,
    Quote,
    RefreshCw,
    Search,
    Share2,
    ShieldCheck,
    Star,
    Tags,
    Trash2,
    Undo2,
    Users,
    X,
} from 'lucide-react';

const ICONS = {
    'align-left': AlignLeft,
    archive: Archive,
    'arrow-down-up': ArrowDownUp,
    'arrow-right': ArrowRight,
    'arrow-up': ArrowUp,
    'bar-chart': BarChart3,
    bug: Bug,
    calendar: CalendarDays,
    'calendar-plus': CalendarPlus,
    check: Check,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'circle-alert': CircleAlert,
    'circle-check': CircleCheck,
    'circle-plus': CirclePlus,
    clock: Clock3,
    columns: Columns3,
    'corner-down-right': CornerDownRight,
    download: Download,
    eye: Eye,
    file: File,
    flag: Flag,
    folder: FolderKanban,
    gantt: GanttChartSquare,
    grip: GripVertical,
    history: History,
    inbox: Inbox,
    layers: Layers3,
    link: Link,
    list: List,
    'list-filter': ListFilter,
    'list-plus': ListPlus,
    'list-todo': ListTodo,
    'list-tree': ListTree,
    maximize: Maximize2,
    menu: Menu,
    message: MessageSquare,
    minimize: Minimize2,
    more: MoreHorizontal,
    move: Move,
    paperclip: Paperclip,
    pencil: Pencil,
    plus: Plus,
    printer: Printer,
    quote: Quote,
    refresh: RefreshCw,
    search: Search,
    share: Share2,
    shield: ShieldCheck,
    star: Star,
    tags: Tags,
    trash: Trash2,
    undo: Undo2,
    users: Users,
    x: X,
};

const Icon = ({ name, className = '', size = 18, strokeWidth = 2, ...props }) => {
    const LucideIcon = ICONS[name] || CircleAlert;
    const classes = ['pandat69-icon', className].filter(Boolean).join(' ');

    return (
        <LucideIcon
            aria-hidden="true"
            className={classes}
            data-pandatask-icon={name}
            focusable="false"
            size={size}
            strokeWidth={strokeWidth}
            {...props}
        />
    );
};

export default Icon;
